
apiVersion: v1
kind: ConfigMap
metadata:
  name: modeldb
  namespace: default
data:
  DEPLOY_ENVIRONMENT: local
  SINGLEUSER_DEFAULT_IAM_ROLE_ARN: fake-local-role
  NAUTH_CALLBACK_BASE: http://localhost:8000
  #SINGLEUSER_IMAGE_SPEC: gitlab-registry.nordstrom.com/platform/frankenstein/jupyterhub:latest
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thevol
  annotations:
       "volume.alpha.kubernetes.io/node-affinity": '{
        "requiredDuringSchedulingIgnoredDuringExecution": {
            "nodeSelectorTerms": [
                { "matchExpressions": [
                    { "key": "kubernetes.io/hostname",
                      "operator": "In",
                      "values": ["docker-for-desktop"]
                    }
                ]}
             ]}
          }'
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath 
  local:
    path: /var/local
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: theclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
